### ISSUE TITLE
[Release1] Post model

### ISSUE THREAD

**Issue by kenkoii** [BottleneckStudio/keepmotivat.in#10]
My idea:
- ID - int64(int)
- Body - string(text, actual content, might be html if oembed object)
- Caption - string(varchar255? text?)
  - Is this optional?
- UserID - int64(int, reference to user who posted)
- Ctime
- Utime

Please add if you have any ideas @rbo13

**Comment by rbo13** [comment]
Seems looks good to me @kenkoii :+1:
