### ISSUE TITLE
[Release1] User model

### ISSUE THREAD

**Issue by rbo13** [BottleneckStudio/keepmotivat.in#16]
Related to: #10.

Possible fields could be:
- ID (primary key)
- Email (varchar(50))
- Password ( hashed -- varchar(255) )
- ConfirmHash (varchar(255) used for: confirm email/forgot password)
- Ctime (int64 -- fixed timestamp)
- Utime (int64 -- fixed timestamp)

Anything I've missed @kenkoii? If ever there is, I will just create anothe PR for the update :)

**Comment by jkbicbic** [comment]
we should discuss this further @kenkoii and @rbo13

**Comment by jkbicbic** [comment]
I think this is already done @rbo13 @kenkoii
